### ISSUE TITLE
Progress Tracker

### ISSUE THREAD

**Issue by tbeswick96** [uksf/launcher-issues#1]
Alpha
- [x] Convert to Electron (big)
- [x] Setup UI for basic starting screen
- [x] Logging
- [ ] Utilise electron auto-updater
- [ ] Utilise SignalR to push updates to clients
- [x] Store settings
- [ ] Full layout of UI for main screen and settings screen
- [x] Login wall using website credentials
- [x] Save credentials
- [x] Encrypt credentials
- [x] Check account access
- [x] Logout on unauthorized API request
- [ ] Utilise SignalR to push account updates to clients
- [x] First Time Setup dialog (Will handle game exe, mod download location, and profile)
- [x] Game installation detection
- [x] Profile selection with automatic detection
- [x] Profile copy option if no UKSF profile found
- [ ] Automatically overwrite profile names using website name
- [ ] Ability to launch the game using startup parameters in settings screen
- [ ] Get running servers from API
- [ ] Join server option
- [ ] Squad URL forcing onto profile (detect prefix, force at each launch)
- [ ] Repo management to API (integrate with API modpack deploy)
- [ ] Data structure for mod files (rewrite)
- [ ] On MP deployment, generate and store delta files for 5(?) versions back
- [ ] Utilise SignalR to push MP updates to clients
- [ ] Client repository checking (rewrite)
- [ ] Client repository caching (rewrite)
- [ ] Client repo updating from API
- [ ] Move repository if mod location changed
- [ ] Launch with mods
- [ ] Sign installer (?)
- [ ] Distribute installer via website
- [ ] Add user documentation

Beta
- [ ] Optimise and clean up anything and everything

**Comment by tbeswick96** [comment]
- [ ] Full layout of UI for main screen and settings screen
- [ ] Add profile selection with automatic detection (in future, update profile from website username)
- [ ] Add ability to launch the game using startup parameters in settings screen
- [ ] Add join server option with server detection (will only display active UKSF servers)
- [ ] Add basic download of modpack
- [ ] Add delta/pbo patching
